# Forge
name: EnlighterJS
author: andidittrich
category: Interface
tags: [parser, syntax highlighter]
demo: http://enlighterjs.andidittrich.de/Themes.html
docs: http://enlighterjs.andidittrich.de
current: v2.10.0-BETA2